# Generated by Django 2.0.6 on 2020-10-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='pic',
            field=models.ImageField(default='917257.jpg', upload_to='pic/'),
        ),
    ]
