# Generated by Django 2.0.6 on 2020-10-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0002_auto_20201029_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='pic',
            field=models.ImageField(default='pic/917257.jpg', upload_to='pic/'),
        ),
    ]
